/**
 * SKR04 → HGB Reverse-Mapping — Bilanz-Konten (0001-3999).
 *
 * Konvention:
 *   - BILANZ_AKTIVA / BILANZ_PASSIVA: Bestandskonten
 *   - HGB §266 Positionen (Aktiva: A./B./C./D., Passiva: A./B./C./D./E.)
 *
 * Confidence-Levels: siehe skr04-reverse-ertrag.ts
 */
import type { ReverseMapping } from './skr04-reverse.types';

export const SKR04_REVERSE_BILANZ: readonly ReverseMapping[] = [
  // Anlagevermögen (Aktiva, HGB §266 Pos. A)
  {
    datevKonto: '0010',
    datevKontoName: 'Grundstücke, grundstücksgleiche Rechte',
    hgbPosition: 'A.II.1.',
    hgbKontoNr: 'Grundstücke',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0080',
    datevKontoName: 'Geschäfts- oder Firmenwert',
    hgbPosition: 'A.I.3.',
    hgbKontoNr: 'Geschäfts- oder Firmenwert',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0100',
    datevKontoName: 'Technische Anlagen und Maschinen',
    hgbPosition: 'A.II.2.',
    hgbKontoNr: 'Technische Anlagen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0200',
    datevKontoName: 'Andere Anlagen, Betriebs- und Geschäftsausstattung',
    hgbPosition: 'A.II.3.',
    hgbKontoNr: 'Andere Anlagen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0300',
    datevKontoName: 'Geleistete Anzahlungen und Anlagen im Bau',
    hgbPosition: 'A.II.4.',
    hgbKontoNr: 'Geleistete Anzahlungen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.9,
  },
  // Finanzanlagen (Aktiva, HGB §266 Pos. A.III)
  {
    datevKonto: '0500',
    datevKontoName: 'Anteile an verbundenen Unternehmen',
    hgbPosition: 'A.III.1.',
    hgbKontoNr: 'Anteile an verbundenen Unternehmen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0600',
    datevKontoName: 'Beteiligungen',
    hgbPosition: 'A.III.3.',
    hgbKontoNr: 'Beteiligungen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '0700',
    datevKontoName: 'Sonstige Ausleihungen',
    hgbPosition: 'A.III.6.',
    hgbKontoNr: 'Sonstige Ausleihungen',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.9,
  },
  // Umlaufvermögen (Aktiva, HGB §266 Pos. B)
  {
    datevKonto: '1000',
    datevKontoName: 'Roh-, Hilfs- und Betriebsstoffe',
    hgbPosition: 'B.I.1.',
    hgbKontoNr: 'Roh-, Hilfs- und Betriebsstoffe',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '1100',
    datevKontoName: 'Unfertige Erzeugnisse',
    hgbPosition: 'B.I.2.',
    hgbKontoNr: 'Unfertige Erzeugnisse',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '1200',
    datevKontoName: 'Fertige Erzeugnisse und Waren',
    hgbPosition: 'B.I.3.',
    hgbKontoNr: 'Fertige Erzeugnisse und Waren',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '1400',
    datevKontoName: 'Forderungen aus Lieferungen und Leistungen',
    hgbPosition: 'B.II.1.',
    hgbKontoNr: 'Forderungen aus L+L',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '1500',
    datevKontoName: 'Sonstige Vermögensgegenstände',
    hgbPosition: 'B.II.4.',
    hgbKontoNr: 'Sonstige Vermögensgegenstände',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.9,
  },
  // Liquide Mittel
  {
    datevKonto: '1600',
    datevKontoName: 'Kassenbestand',
    hgbPosition: 'B.IV.',
    hgbKontoNr: 'Kassenbestand',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: true,
    confidence: 1.0,
  },
  {
    datevKonto: '1800',
    datevKontoName: 'Guthaben bei Kreditinstituten (Bank)',
    hgbPosition: 'B.IV.',
    hgbKontoNr: 'Bankguthaben',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: true,
    confidence: 1.0,
  },
  // Rechnungsabgrenzungsposten aktiv
  {
    datevKonto: '1900',
    datevKontoName: 'Rechnungsabgrenzungsposten (aktiv)',
    hgbPosition: 'C.',
    hgbKontoNr: 'Rechnungsabgrenzungsposten (aktiv)',
    kategorie: 'BILANZ_AKTIVA',
    side: 'AKTIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  // Eigenkapital (Passiva, HGB §266 Pos. A)
  {
    datevKonto: '2000',
    datevKontoName: 'Gezeichnetes Kapital',
    hgbPosition: 'A.I.',
    hgbKontoNr: 'Gezeichnetes Kapital',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: true,
    confidence: 1.0,
  },
  {
    datevKonto: '2100',
    datevKontoName: 'Kapitalrücklage',
    hgbPosition: 'A.II.',
    hgbKontoNr: 'Kapitalrücklage',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '2200',
    datevKontoName: 'Gewinnrücklagen',
    hgbPosition: 'A.III.',
    hgbKontoNr: 'Gewinnrücklagen',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '2300',
    datevKontoName: 'Gewinnvortrag / Verlustvortrag',
    hgbPosition: 'A.IV.',
    hgbKontoNr: 'Gewinnvortrag/Verlustvortrag',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '2400',
    datevKontoName: 'Jahresüberschuss / Jahresfehlbetrag',
    hgbPosition: 'A.V.',
    hgbKontoNr: 'Jahresüberschuss/-fehlbetrag',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: true,
    confidence: 1.0,
  },
  // Rückstellungen (Passiva, HGB §266 Pos. B)
  {
    datevKonto: '3000',
    datevKontoName: 'Pensionsrückstellungen',
    hgbPosition: 'B.1.',
    hgbKontoNr: 'Pensionsrückstellungen',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '3100',
    datevKontoName: 'Steuerrückstellungen',
    hgbPosition: 'B.2.',
    hgbKontoNr: 'Steuerrückstellungen',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '3200',
    datevKontoName: 'Sonstige Rückstellungen',
    hgbPosition: 'B.3.',
    hgbKontoNr: 'Sonstige Rückstellungen',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  // Verbindlichkeiten (Passiva, HGB §266 Pos. C)
  {
    datevKonto: '3300',
    datevKontoName: 'Verbindlichkeiten aus Lieferungen und Leistungen',
    hgbPosition: 'C.4.',
    hgbKontoNr: 'Verbindlichkeiten aus L+L',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '3400',
    datevKontoName: 'Verbindlichkeiten gegenüber Kreditinstituten',
    hgbPosition: 'C.2.',
    hgbKontoNr: 'Verbindlichkeiten gegenüber Kreditinstituten',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '3500',
    datevKontoName: 'Sonstige Verbindlichkeiten',
    hgbPosition: 'C.8.',
    hgbKontoNr: 'Sonstige Verbindlichkeiten',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.85,
  },
  // Rechnungsabgrenzungsposten passiv
  {
    datevKonto: '3700',
    datevKontoName: 'Rechnungsabgrenzungsposten (passiv)',
    hgbPosition: 'D.',
    hgbKontoNr: 'Rechnungsabgrenzungsposten (passiv)',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
  // Passive latente Steuern
  {
    datevKonto: '3800',
    datevKontoName: 'Passive latente Steuern',
    hgbPosition: 'E.',
    hgbKontoNr: 'Passive latente Steuern',
    kategorie: 'BILANZ_PASSIVA',
    side: 'PASSIVA',
    isPflicht: false,
    confidence: 0.95,
  },
];