/**
 * SKR04 → HGB Reverse-Mapping — Aufwandskonten (5000-7999).
 *
 * Konvention:
 *   - MATERIAL (HGB §275 Position 5) — Materialaufwand
 *   - PERSONAL (HGB §275 Position 6) — Personalaufwand
 *   - ABSCHREIBUNG (HGB §275 Position 7) — Abschreibungen
 *   - SONSTIGE_AUFWAND (HGB §275 Position 8) — Sonstige betriebliche Aufwendungen
 *   - FINANZ (HGB §275 Position 12-13) — Zinsen / Finanzergebnis
 *   - STEUER (HGB §275 Position 14-16) — Steuern
 *
 * Confidence-Levels: siehe skr04-reverse-ertrag.ts
 */
import type { ReverseMapping } from './skr04-reverse.types';

export const SKR04_REVERSE_AUFWAND: readonly ReverseMapping[] = [
  // Materialaufwand (HGB §275 Pos. 5)
  {
    datevKonto: '5000',
    datevKontoName: 'Materialaufwand',
    hgbPosition: '5a.',
    hgbKontoNr: 'Materialaufwand',
    kategorie: 'MATERIAL',
    side: 'NEUTRAL',
    isPflicht: true,
    confidence: 0.95,
  },
  {
    datevKonto: '5100',
    datevKontoName: 'Wareneinsatz',
    hgbPosition: '5a.',
    hgbKontoNr: 'Materialaufwand',
    kategorie: 'MATERIAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '5200',
    datevKontoName: 'Bezogene Leistungen',
    hgbPosition: '5b.',
    hgbKontoNr: 'Bezogene Leistungen',
    kategorie: 'MATERIAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  // Personalaufwand (HGB §275 Pos. 6)
  {
    datevKonto: '6000',
    datevKontoName: 'Personalaufwand',
    hgbPosition: '6.',
    hgbKontoNr: 'Personalaufwand',
    kategorie: 'PERSONAL',
    side: 'NEUTRAL',
    isPflicht: true,
    confidence: 0.95,
  },
  {
    datevKonto: '6010',
    datevKontoName: 'Löhne',
    hgbPosition: '6a.',
    hgbKontoNr: 'Löhne',
    kategorie: 'PERSONAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6020',
    datevKontoName: 'Gehälter',
    hgbPosition: '6a.',
    hgbKontoNr: 'Gehälter',
    kategorie: 'PERSONAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6030',
    datevKontoName: 'Soziale Abgaben',
    hgbPosition: '6b.',
    hgbKontoNr: 'Soziale Abgaben',
    kategorie: 'PERSONAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6040',
    datevKontoName: 'Altersversorgung',
    hgbPosition: '6b.',
    hgbKontoNr: 'Altersversorgung',
    kategorie: 'PERSONAL',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.85,
  },
  // Abschreibungen (HGB §275 Pos. 7)
  {
    datevKonto: '6200',
    datevKontoName: 'Abschreibungen',
    hgbPosition: '7a.',
    hgbKontoNr: 'Abschreibungen',
    kategorie: 'ABSCHREIBUNG',
    side: 'NEUTRAL',
    isPflicht: true,
    confidence: 0.95,
  },
  {
    datevKonto: '6210',
    datevKontoName: 'Abschreibungen auf Sachanlagen',
    hgbPosition: '7a.',
    hgbKontoNr: 'Abschreibungen auf Sachanlagen',
    kategorie: 'ABSCHREIBUNG',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  // Sonstige betriebliche Aufwendungen (HGB §275 Pos. 8)
  {
    datevKonto: '6300',
    datevKontoName: 'Sonstige Raumkosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Sonstige betriebliche Aufwendungen',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.85,
  },
  {
    datevKonto: '6310',
    datevKontoName: 'Miete',
    hgbPosition: '8.',
    hgbKontoNr: 'Miete',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6320',
    datevKontoName: 'Pacht',
    hgbPosition: '8.',
    hgbKontoNr: 'Pacht',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '6400',
    datevKontoName: 'Energiekosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Energiekosten',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6500',
    datevKontoName: 'Kfz-Kosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Kfz-Kosten',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6600',
    datevKontoName: 'Reisekosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Reisekosten',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '6700',
    datevKontoName: 'Kosten Warenabgabe',
    hgbPosition: '8.',
    hgbKontoNr: 'Sonstige betriebliche Aufwendungen',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.7,
  },
  {
    datevKonto: '6800',
    datevKontoName: 'Bürobedarf',
    hgbPosition: '8.',
    hgbKontoNr: 'Bürobedarf',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '6900',
    datevKontoName: 'Telekommunikation',
    hgbPosition: '8.',
    hgbKontoNr: 'Telekommunikation',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '7000',
    datevKontoName: 'Werbekosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Werbekosten',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '7100',
    datevKontoName: 'Repräsentationskosten',
    hgbPosition: '8.',
    hgbKontoNr: 'Repräsentationskosten',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.85,
  },
  {
    datevKonto: '7200',
    datevKontoName: 'Instandhaltung',
    hgbPosition: '8.',
    hgbKontoNr: 'Instandhaltung',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '7300',
    datevKontoName: 'Versicherungen',
    hgbPosition: '8.',
    hgbKontoNr: 'Versicherungen',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.9,
  },
  {
    datevKonto: '7400',
    datevKontoName: 'Beiträge und Gebühren',
    hgbPosition: '8.',
    hgbKontoNr: 'Beiträge und Gebühren',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.85,
  },
  // Finanzergebnis (HGB §275 Pos. 12-13)
  {
    datevKonto: '7500',
    datevKontoName: 'Zinsaufwendungen',
    hgbPosition: '13.',
    hgbKontoNr: 'Zinsaufwendungen',
    kategorie: 'FINANZ',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  // Steuern (HGB §275 Pos. 14-16)
  {
    datevKonto: '7600',
    datevKontoName: 'Steuern vom Einkommen und Ertrag',
    hgbPosition: '14.',
    hgbKontoNr: 'Steuern vom Einkommen und Ertrag',
    kategorie: 'STEUER',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '7700',
    datevKontoName: 'Sonstige Steuern',
    hgbPosition: '16.',
    hgbKontoNr: 'Sonstige Steuern',
    kategorie: 'STEUER',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.95,
  },
  {
    datevKonto: '7800',
    datevKontoName: 'Rückstellungszuführungen',
    hgbPosition: '8.',
    hgbKontoNr: 'Sonstige betriebliche Aufwendungen',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.7,
  },
  {
    datevKonto: '7900',
    datevKontoName: 'Sonstige Aufwendungen',
    hgbPosition: '8.',
    hgbKontoNr: 'Sonstige betriebliche Aufwendungen',
    kategorie: 'SONSTIGE_AUFWAND',
    side: 'NEUTRAL',
    isPflicht: false,
    confidence: 0.5,
    notes: 'Sammelkonto — manuelle Aufsplittung in 8a/8b/8c erforderlich.',
  },
];